# Generated by Django 5.1.2 on 2024-11-17 07:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0002_payment_order_details'),
    ]

    operations = [
        migrations.RenameField(
            model_name='payment',
            old_name='razopay_payment_id',
            new_name='razorpay_payment_id',
        ),
    ]
