# Generated by Django 5.1.2 on 2024-11-17 07:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0003_rename_razopay_payment_id_payment_razorpay_payment_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order_details',
            old_name='phoneno',
            new_name='phone_no',
        ),
    ]
