# Generated by Django 5.1.2 on 2024-11-17 07:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0004_rename_phoneno_order_details_phone_no'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order_details',
            old_name='phone_no',
            new_name='phoneno',
        ),
    ]
